required_plugins = %w( landrush )
required_plugins.each do |plugin|
  system "vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
end

# Running vagrant up will result in a Virtuabox VM with docker registry running
# Endpoint: registry.vagrant:5000

Vagrant.configure('2') do |config|

  config.vm.provider 'virtualbox' do |v|
    v.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
    v.memory = 1024
    v.cpus = 1
  end

  config.vm.define 'registry' do |registry|
    registry.vm.box_url =
        'https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box'
    registry.vm.box = 'trusty-server-cloudimg-amd64-vagrant-disk1.box'
    registry.vm.hostname = 'registry.vagrant'
    registry.landrush.enabled = true
    registry.landrush.tld = 'vagrant'
    registry.landrush.host 'registry.vagrant'
    registry.landrush.guest_redirect_dns = false

    registry.vm.provision :chef_solo do |chef|
      chef.channel = 'stable'
      chef.version = '12.5.1'
      chef.cookbooks_path = '../../cookbooks'
      chef.add_recipe 'luxoft_docker::registry'
      chef.json = {}
    end
  end

end