required_plugins = %w( vagrant-vbguest vagrant-omnibus )
required_plugins.each do |plugin|
  system "vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
end

Vagrant.configure('2') do |config|

  config.vm.provider 'virtualbox' do |v|
    v.memory = 4096
    v.cpus = 2
  end

  #TODO create our own vagrant boxes

  config.vm.define 'default' do |default|
    default.vm.box_url =
      'https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box'
    default.vm.box = 'trusty-server-cloudimg-amd64-vagrant-disk1.box'
    default.vm.network 'private_network', ip: '192.168.20.2'
    default.vm.provision :chef_solo do |chef|
      chef.cookbooks_path = '../../cookbooks'
      chef.add_recipe 'luxoft_docker_jenkins'
      chef.json = {}
    end
  end

end
